# Generated by Django 5.0.4 on 2025-02-08 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En construcción', 'En construcción'), ('Cerrado', 'Cerrado')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('puntuacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espacio.cliente')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espacio.espacio')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoConstruccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('En progreso', 'En progreso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], max_length=50)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espacio.espacio')),
            ],
        ),
    ]
