# Generated by Django 5.0.4 on 2025-02-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espacio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='espacio'),
        ),
        migrations.AddField(
            model_name='proyectoconstruccion',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='proyecto'),
        ),
    ]
