# Generated by Django 5.0.4 on 2025-02-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espacio', '0002_espacio_foto_proyectoconstruccion_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('detalle', models.TextField()),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='emails')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
