# Generated by Django 5.0.4 on 2025-02-10 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espacio', '0003_sugerencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencia',
            name='apellido',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El apellido solo puede contener letras.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos.', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese un correo válido.')]),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias'),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='nombre',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras.', regex='^[a-zA-Z]+$')]),
        ),
    ]
