# Generated by Django 5.0.4 on 2025-02-10 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espacio', '0004_alter_sugerencia_apellido_alter_sugerencia_cedula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='espacio',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='notificar',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Espacio.proyectoconstruccion'),
            preserve_default=False,
        ),
    ]
